In [1]:
import numpy as np

In [2]:
list = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]

In [5]:
arr=np.array(list)

In [6]:
print(arr*4)

[ 80 108  36  48 124  68  16 200 156 140]


In [7]:
print(np.mean(arr))

24.4


In [8]:
print(np.median(arr))

23.5


In [9]:
print(np.std(arr))

13.828955130450023


In [10]:
np.argmin(arr)

np.int64(6)

In [11]:
np.argmax(arr)

np.int64(7)

In [12]:
print(np.argmax(arr))

7


In [13]:
print(arr[np.argmax(arr)])

50


In [14]:
print(arr[np.argmin(arr)])

4


In [15]:
print(np.min(arr))

4


In [16]:
print(np.max(arr))

50


In [17]:
greater=arr[arr>20]
print(greater)

[27 31 50 39 35]


In [18]:
matrix = [
    [5, 12, 17, 9],
    [8, 21, 14, 3],
    [6, 13, 19, 11]
]
arr = np.array(matrix)

In [19]:
print(arr.shape)

(3, 4)


In [20]:
print(arr[:, 2])

[17 14 19]


In [22]:
print(arr[1, :])

[ 8 21 14  3]


In [23]:
print(arr*2)

[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]


In [24]:
column_means = np.mean(arr, axis=0)
print(column_means)

[ 6.33333333 15.33333333 16.66666667  7.66666667]


In [25]:
print(np.mean(arr))

11.5


In [26]:
max = np.max(arr, axis=1)
min = np.min(arr, axis=0)
print(max)
print(min)

[17 21 19]
[ 5 12 14  3]


In [27]:
flattened = arr.flatten()

In [28]:
print(flattened)
print(flattened.shape)

[ 5 12 17  9  8 21 14  3  6 13 19 11]
(12,)


In [29]:
min = np.argmin(flattened)
max = np.argmax(flattened)
print(min)
print(max)

7
5


In [30]:
min1 = np.unravel_index(min, arr.shape)
max1 = np.unravel_index(max, arr.shape)
print(min1)
print(max1)

(np.int64(1), np.int64(3))
(np.int64(1), np.int64(1))


In [31]:
print(arr[arr > 15])

[17 21 19]


In [32]:
print(np.sort(arr, axis=1))

[[ 5  9 12 17]
 [ 3  8 14 21]
 [ 6 11 13 19]]


In [33]:
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

In [38]:
def get_rows_with_primes(arr):
    result_rows = []
    
    for i in range(arr.shape[0]):
        row = False
        for j in range(arr.shape[1]):
            if is_prime(arr[i, j]):
                row = True
                break
        if row:
            result_rows.append(arr[i])
    return np.array(result_rows)

In [39]:
arr = np.array([
    [2, 3, 5],
    [14, 6, 8],
    [11, 13, 17],
    [7, 10, 13]
])

In [40]:
print(get_rows_with_primes(arr))

[[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]


In [46]:
def checkerboard():
    board = np.zeros((8, 8), dtype=int)
    for i in range(8):
        for j in range(8):
            if i % 2 == 0:
                if j % 2 == 0:
                    board[i, j] = 1
            else: 
                if j % 2 == 1:
                    board[i, j] = 1
    return board

In [47]:
def reverse():
    board = np.zeros((8, 8), dtype=int)
    
    for i in range(8):
        for j in range(8):
            if i % 2 == 0:
                if j % 2 == 1:
                    board[i, j] = 1
            else:
                if j % 2 == 0:
                    board[i, j] = 1
    return board

In [48]:
def expansion(strings, spaces):
    result = []
    space = ' ' * spaces
    
    for s in strings:
        expanded = space.join(s)
        result.append(expanded)
    
    return np.array(result)